{% set name = "pykerberos" %}
{% set version = "1.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9d701ebd8fc596c99d3155d5ba45813bd5908d26ef83ba0add250edb622abed4
  patches:
    # fix issue with memcpy on macOS
    # LICENSE: this patch is reproduced from the AnacondaRecipes/aggregate
    #          recipe for this package, with permission from the author, see
    #          https://github.com/conda-forge/staged-recipes/pull/10646#issuecomment-576312814
    - 0001-Implement-mempcpy-via-memcpy.patch  # [osx]

build:
  number: 4
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - krb5
    - pip
    - python
    - setuptools
  run:
    - krb5
    - python

test:
  imports:
    - kerberos

about:
  home: https://github.com/02strich/pykerberos
  dev_url: https://github.com/02strich/pykerberos
  doc_url: https://pypi.python.org/pypi/kerberos
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: High-level interface to Kerberos
  description: |
    pykerberos is a high-level wrapper for Kerberos (GSSAPI) operations. The
    goal is to avoid having to build a module that wraps the entire
    Kerberos.framework and instead offer a limited set of functions that do
    what is needed for client/server Kerberos authentication.

extra:
  recipe-maintainers:
    - duncanmmacleod
